Explain
version: '1.0'
stages:
  - prepare
  - build
steps:
  main_clone:
    title: Cloning main repository...
    stage: prepare
    type: git-clone
    repo: 'tanu8204/Vendor-'
    revision: main
    git: github
  BuildingDockerImage:
    title: Building Docker Image
    stage: build
    type: build
    image_name: Vendor-
    working_directory: ./
    tag: 'multi-stage'
    dockerfile: Dockerfile
