name: Render Deploy

on:
  push:
    branches:
      - main  # Adjust this to match your main branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'

      - name: Build with Gradle
        run: ./gradlew build --no-daemon

      - name: Deploy to Render
        uses: tanu8204/Vendor-
        with:
          renderToken: ${{ secrets.RENDER_TOKEN }}
          args: --branch=main --build-only
